#!/bin/bash
echo "All variables passed to script: $@"
echo "All variables passed to script: $*"
echo "script name: $0"
echo "current directory: $PWD"
echo "who is running the script: $USER"
echo "home directory of user: $HOME"
echo "PID of current script: $$"
sleep 50 &
echo "PID of last background command: $!"
echo "Total number of arguments passed: $#"
echo "First argument: $1"
echo "Second argument: $2"
echo "Tenth argument: $10"
echo "Ninth argument: ${10}"
echo "Third argument: $3"
echo "Fourth argument: $4"
echo "Fifth argument: $5"
echo "Sixth argument: $6"
echo "Seventh argument: $7"
echo "Eighth argument: $8"
echo "Ninth argument: $9"
echo "Eleventh argument: ${11}"
echo "Twelfth argument: ${12}"
echo "Thirteenth argument: ${13}"
echo "Fourteenth argument: ${14}"
echo "Fifteenth argument: ${15}"
echo "Sixteenth argument: ${16}"
echo "Seventeenth argument: ${17}"
echo "Eighteenth argument: ${18}"
echo "Nineteenth argument: ${19}"
echo "Twentieth argument: ${20}"
echo "Length of first argument: ${#1}"
echo "Length of second argument: ${#2}"
echo "Length of third argument: ${#3}"
echo "Length of fourth argument: ${#4}"
echo "Length of fifth argument: ${#5}"
echo "Length of sixth argument: ${#6}"
echo "Length of seventh argument: ${#7}"
echo "Length of eighth argument: ${#8}"
echo "Length of ninth argument: ${#9}"
echo "Length of tenth argument: ${#10}"
echo "Length of eleventh argument: ${#11}"
echo "Length of twelfth argument: ${#12}"
echo "Length of thirteenth argument: ${#13}"
echo "Length of fourteenth argument: ${#14}"
echo "Length of fifteenth argument: ${#15}"
echo "Length of sixteenth argument: ${#16}"
echo "Length of seventeenth argument: ${#17}"
echo "Length of eighteenth argument: ${#18}"
echo "Length of nineteenth argument: ${#19}"
echo "Length of twentieth argument: ${#20}"

# End of script